// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1BbSCCPZ3m8FQMzS6WXmVJV8CDfVfRIg',
    appId: '1:917866687436:web:9df0f5579d9a0b7cb40b69',
    messagingSenderId: '917866687436',
    projectId: 'booknest-54526',
    authDomain: 'booknest-54526.firebaseapp.com',
    storageBucket: 'booknest-54526.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnntUDrKq6DF1lULwQIzpyVr4m1VnF03I',
    appId: '1:917866687436:android:1cd4c7c1c611009db40b69',
    messagingSenderId: '917866687436',
    projectId: 'booknest-54526',
    storageBucket: 'booknest-54526.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4VYvqJ0ln45sc7jrG55nromwlkWR4xec',
    appId: '1:917866687436:ios:c652f05db53f75b6b40b69',
    messagingSenderId: '917866687436',
    projectId: 'booknest-54526',
    storageBucket: 'booknest-54526.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4VYvqJ0ln45sc7jrG55nromwlkWR4xec',
    appId: '1:917866687436:ios:c652f05db53f75b6b40b69',
    messagingSenderId: '917866687436',
    projectId: 'booknest-54526',
    storageBucket: 'booknest-54526.firebasestorage.app',
    iosBundleId: 'com.example.booknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1BbSCCPZ3m8FQMzS6WXmVJV8CDfVfRIg',
    appId: '1:917866687436:web:8a835289acb487c2b40b69',
    messagingSenderId: '917866687436',
    projectId: 'booknest-54526',
    authDomain: 'booknest-54526.firebaseapp.com',
    storageBucket: 'booknest-54526.firebasestorage.app',
  );
}
