name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # triggers on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- corrected

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'  # your Flutter version

      # Get dependencies
      - run: flutter pub get

      # Build web
      - run: flutter build web

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: build/web
